export class Player {
    constructor(
        public id:number,
        public PhotoUrl:string,
        public name:string,
        public team:string,
        public position:string
    ) {}
}

export interface OffensivePlayer extends Player {
    fantasyPosition:string,
    number:number,
    passingAttempts:number,
    passingCompletions:number,
    passingYards:number,
    passingCompletionPercentage:number,
    passingYardsPerAttempt:number,
    passingYardsPerCompletion:number,
    passingTouchdowns:number,
    passingInterceptions:number,
    passingRating:number,
    passingLong:number,
    passingSacks:number,
    passingSackYards:number,
    rushingAttempts:number,
    rushingYards:number,
    rushingYardsPerAttempt:number,
    rushingTouchdowns:number,
    rushingLong:number,
    receivingTargets:number,
    receptions:number,
    receivingYards:number,
    receivingYardsPerReception:number,
    receivingTouchdowns:number,
    receivingLong:number,
    fumbles:number,
    fumblesLost:number,
    puntReturns:number,
    puntReturnYards:number,
    puntReturnTouchdowns:number,
    puntReturnYardsPerAttempt:number,
    puntReturnLong:number,
    kickReturns:number,
    kickReturnYards:number, 
    kickReturnYardsPerAttempt:number,
    kickReturnTouchdowns:number,
    kickReturnLong:number,
    interceptions:number,
    twoPointConversionPasses:number,
    twoPointConversionRuns:number,
    twoPointConversionReceptions:number,
    fantasyPoints:number,
    fantasyPointsPPR:number,
    fantasyPointsFanDuel:number,
    fantasyPointsDraftKings:number,
    fantasyPointsYahoo:number,
    fantasyPointsFantasyDraft:number
}

export interface DefensivePlayer extends Player {
    fantasyPosition:string,
    number:number,
    soloTackles:number,
    assistedTackles:number,
    tacklesForLoss:number,
    sacks:number,
    sackYards:number,
    quarterbackHits:number,
    passesDefended:number,
    fumblesForced:number,
    fumblesRecovered:number,
    fumbleReturnYards:number,
    fumbleReturnTouchdowns:number,
    interceptions:number,
    interceptionReturnYards:number,
    interceptionReturnTouchdowns:number,
    blockedKicks:number,
    fantasyPoints:number,
    fantasyPointsPPR:number,
    fantasyPointsFanDuel:number,
    fantasyPointsDraftKings:number,
    fantasyPointsYahoo:number,
    fantasyPointsFantasyDraft:number
}

export interface Kicker {
    position:string,
    fantasyPosition:string,
    number:number,
    punts:number,
    puntYards:number,
    puntAverage:number,
    fieldGoalsAttempted:number,
    fieldGoalsMade:number,
    fieldGoalsLongestMade:number,
    extraPointsMade:number,
    fieldGoalsMade0to19:number,
    fieldGoalsMade20to29:number,
    fieldGoalsMade30to39:number,
    fieldGoalsMade40to49:number,
    fieldGoalsMade50Plus:number,
    fantasyPoints:number,
    fantasyPointsPPR:number,
    fantasyPointsFanDuel:number,
    fantasyPointsDraftKings:number,
    fantasyPointsYahoo:number,
    fantasyPointsFantasyDraft:number
}

export type NFLPlayer = OffensivePlayer | DefensivePlayer | Kicker 