export interface Team {
    key:string,
    teamID:number,
    city:string,
    name:string,
    conference:string,
    division:string,
    fullName:string,
    stadiumID:number,
    primaryColor:string,
    secondaryColor:string,
    wikipediaLogoUrl:string,
    wikipediaWordMarkUrl:string,
    wins:number, 
    losses:number,
    ties:number
    conferenceRank:number,
    conferenceWins:number,
    conferenceLosses:number,
    conferenceTies:number,
    divisionRank:number
    divisionWins:number,
    divisionLosses:number,
    divisionTies:number
}